"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import type { CSSProperties } from "react";
import { useEffect, useMemo, useState } from "react";

type Kind = "EXPENSE" | "INCOME";
type Category = { id:string; kind:Kind; name:string; parentId:string|null; depth:number; color:string|null };
type Person = { id:string; name:string };
type Merchant = { id:string; name:string };
type Tab = "expense" | "income" | "people" | "merchants" | "learning";
type TreeNode = Category & { children:TreeNode[]; path:string };
type MappingRule = { id:string;merchantNormalized:string;rawNormalized:string;label:string;reusableItemName:string|null;categoryId:string|null;categoryPath:string;usageCount:number;lastUsedAt:string;updatedAt:string;isDairy:boolean;containsEgg:boolean;containsAnimal:boolean;isAlcohol:boolean;isFrozen:boolean;isCanned:boolean;isPackaged:boolean };
type StructureRule = { id:string;merchantNormalized:string;signature:string;action:"MERGE"|"SPLIT";components:unknown[];targetLabel:string|null;targetCategoryId:string|null;targetCategoryPath:string;targetReusableItemName:string|null;usageCount:number;lastUsedAt:string;updatedAt:string };

function makeTree(categories:Category[],kind:Kind):TreeNode[]{
 const relevant=categories.filter(c=>c.kind===kind),byId=new Map<string,TreeNode>();
 for(const c of relevant)byId.set(c.id,{...c,children:[],path:c.name});
 const roots:TreeNode[]=[];for(const node of byId.values()){if(node.parentId&&byId.has(node.parentId))byId.get(node.parentId)!.children.push(node);else roots.push(node)}
 const walk=(nodes:TreeNode[],prefix="")=>{nodes.sort((a,b)=>a.name.localeCompare(b.name,"hu"));for(const node of nodes){node.path=prefix?`${prefix} › ${node.name}`:node.name;walk(node.children,node.path)}};walk(roots);return roots;
}
function categoryPath(categories:Category[],id:string|null){if(!id)return"";const byId=new Map(categories.map(c=>[c.id,c]));const parts:string[]=[];let cur=byId.get(id);while(cur){parts.unshift(cur.name);cur=cur.parentId?byId.get(cur.parentId):undefined}return parts.join(" › ")}
function merchantLabel(value:string){return value==="*"?"Minden bolt":value||"Ismeretlen bolt"}
function dateLabel(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?"":d.toLocaleString("hu-HU",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}

function CategoryNodeButton({node,accent,selectedId,onSelect}:{node:TreeNode;accent:string;selectedId:string|null;onSelect:(node:TreeNode,accent:string)=>void}){
 return <div className="db-tree-node"><button type="button" className={`db-tree-button depth-${node.depth} ${selectedId===node.id?"active":""}`} onClick={()=>onSelect(node,accent)} style={{"--node-accent":accent} as CSSProperties}><span className="db-node-main"><span className="db-color-dot"/><span>{node.name}</span></span><span className="db-node-meta">{node.children.length?`${node.children.length}`:`L${node.depth}`}</span></button>{node.children.length>0&&<div className="db-tree-children">{node.children.map(child=><CategoryNodeButton key={child.id} node={child} accent={accent} selectedId={selectedId} onSelect={onSelect}/>)}</div>}</div>;
}

export function DatabaseManager({categories,people,merchants}:{categories:Category[];people:Person[];merchants:Merchant[]}){
 const router=useRouter();
 const [tab,setTab]=useState<Tab>("expense"),[selectedId,setSelectedId]=useState<string|null>(null),[selectedAccent,setSelectedAccent]=useState("#AFC9E8");
 const [name,setName]=useState(""),[newName,setNewName]=useState(""),[newColor,setNewColor]=useState("#AFC9E8"),[selectedColor,setSelectedColor]=useState("#AFC9E8"),[newAsItem,setNewAsItem]=useState(false);
 const [personName,setPersonName]=useState(""),[merchantName,setMerchantName]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [mappings,setMappings]=useState<MappingRule[]>([]),[structureRules,setStructureRules]=useState<StructureRule[]>([]),[learningLoading,setLearningLoading]=useState(false),[learningFilter,setLearningFilter]=useState(""),[learningView,setLearningView]=useState<"mapping"|"structure">("mapping");
 const expenseTree=useMemo(()=>makeTree(categories,"EXPENSE"),[categories]),incomeTree=useMemo(()=>makeTree(categories,"INCOME"),[categories]);
 const selected=categories.find(c=>c.id===selectedId)??null,flatPath=useMemo(()=>selected?categoryPath(categories,selected.id):"",[categories,selected]);
 const expenseCategories=useMemo(()=>categories.filter(c=>c.kind==="EXPENSE"),[categories]);

 async function loadLearning(){setLearningLoading(true);setError("");const res=await fetch("/api/database/receipt-learning",{cache:"no-store"});const data=await res.json().catch(()=>({}));setLearningLoading(false);if(!res.ok)return setError(data.error??"A tanulási szabályok nem tölthetők be.");setMappings(data.mappings??[]);setStructureRules(data.structureRules??[])}
 useEffect(()=>{if(tab==="learning")void loadLearning()},[tab]);
 function selectNode(node:TreeNode,accent:string){setSelectedId(node.id);setSelectedAccent(accent);setSelectedColor(node.color??accent);setName(node.name);setNewName("");setNewAsItem(node.depth===2);setMessage("");setError("")}
 function closeInspector(){setSelectedId(null);setName("");setNewName("")}
 async function mutate(url:string,method:string,body:unknown){setBusy(true);setError("");setMessage("");const res=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));setBusy(false);if(!res.ok){setError(data.error??"A művelet nem sikerült.");return null}router.refresh();return data}
 async function learningMutate(method:string,body:unknown,success:string){setBusy(true);setError("");const res=await fetch("/api/database/receipt-learning",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));setBusy(false);if(!res.ok)return setError(data.error??"A tanulási szabály módosítása nem sikerült.");setMessage(success);await loadLearning()}

 async function addCategory(kind:Kind,parentId:string|null){const trimmed=newName.trim();if(!trimmed)return setError("Adj nevet az új elemnek.");const parent=parentId?categories.find(c=>c.id===parentId):null,nextDepth=parent?parent.depth+1:1;const result=await mutate("/api/database/categories","POST",{kind,name:trimmed,parentId,color:parentId?null:newColor,createReusableItem:parentId?(newAsItem||nextDepth===3):false});if(result){setNewName("");setNewAsItem(false);setMessage("Az új elem létrejött.")}}
 async function updateCategory(){if(!selected||!name.trim())return;const result=await mutate("/api/database/categories","PATCH",{id:selected.id,name:name.trim(),color:selectedColor});if(result){setSelectedAccent(selectedColor);setMessage("Az elem frissítve.")}}
 async function removeCategory(){if(!selected||!confirm(`Biztosan törlöd vagy archiválod ezt: ${flatPath}?`))return;const result=await mutate("/api/database/categories","DELETE",{id:selected.id});if(result){closeInspector();setMessage(result.mode==="archived"?"Használt elem volt, ezért archiválva lett.":"Az elem törölve lett.")}}
 async function addPerson(){if(!personName.trim())return;const result=await mutate("/api/database/people","POST",{name:personName.trim()});if(result){setPersonName("");setMessage("Személy hozzáadva.")}}
 async function renamePerson(person:Person){const next=prompt("Új név",person.name)?.trim();if(!next||next===person.name)return;const result=await mutate("/api/database/people","PATCH",{id:person.id,name:next});if(result)setMessage("Személy frissítve.")}
 async function removePerson(person:Person){if(!confirm(`Biztosan törlöd vagy archiválod: ${person.name}?`))return;const result=await mutate("/api/database/people","DELETE",{id:person.id});if(result)setMessage(result.mode==="archived"?"A személy korábbi adatok miatt archiválva lett.":"A személy törölve lett.")}
 async function addMerchant(){if(!merchantName.trim())return;const result=await mutate("/api/database/merchants","POST",{name:merchantName.trim()});if(result){setMerchantName("");setMessage("Partner hozzáadva.")}}
 async function renameMerchant(merchant:Merchant){const next=prompt("Új név",merchant.name)?.trim();if(!next||next===merchant.name)return;const result=await mutate("/api/database/merchants","PATCH",{id:merchant.id,name:next});if(result)setMessage("Partner frissítve.")}
 async function removeMerchant(merchant:Merchant){if(!confirm(`Biztosan törlöd vagy archiválod: ${merchant.name}?`))return;const result=await mutate("/api/database/merchants","DELETE",{id:merchant.id});if(result)setMessage(result.mode==="archived"?"A partner korábbi adatok miatt archiválva lett.":"A partner törölve lett.")}

 const currentKind:Kind=tab==="income"?"INCOME":"EXPENSE",currentTree=currentKind==="EXPENSE"?expenseTree:incomeTree;
 const needle=learningFilter.trim().toLocaleLowerCase("hu-HU");
 const visibleMappings=mappings.filter(m=>!needle||[m.rawNormalized,m.label,m.categoryPath,m.merchantNormalized].some(v=>v.toLocaleLowerCase("hu-HU").includes(needle)));
 const visibleStructures=structureRules.filter(r=>!needle||[r.action,r.targetLabel??"",r.targetCategoryPath,r.merchantNormalized,...r.components.map(v=>String(v))].some(v=>v.toLocaleLowerCase("hu-HU").includes(needle)));

 return <div className="db-manager">
  <div className="db-tabs">
   <button className={tab==="expense"?"active expense":""} onClick={()=>{setTab("expense");closeInspector()}}>Kiadási fa</button><button className={tab==="income"?"active income":""} onClick={()=>{setTab("income");closeInspector()}}>Bevételi fa</button><button className={tab==="people"?"active people":""} onClick={()=>{setTab("people");closeInspector()}}>Személyek</button><button className={tab==="merchants"?"active merchant":""} onClick={()=>{setTab("merchants");closeInspector()}}>Boltok / partnerek</button><button className={tab==="learning"?"active learning":""} onClick={()=>{setTab("learning");closeInspector()}}>AI tanulás</button>
  </div>
  {error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}

  {(tab==="expense"||tab==="income")&&<section className="panel db-tree-panel"><div className="panel-head db-panel-head"><div><h2>{tab==="expense"?"Kiadási kategóriák":"Bevételi kategóriák"}</h2><p className="muted db-help">A színek a fő kategóriát követik. Kattints egy elemre a kezeléshez vagy gyors bevitelhez.</p></div></div><div className="db-root-create"><input className="input" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Új fő kategória"/><label className="db-color-picker"><input className="color-input" type="color" value={newColor} onChange={e=>setNewColor(e.target.value)} aria-label="Kategória színe"/><span>{newColor.toUpperCase()}</span></label><button className="secondary" disabled={busy} onClick={()=>addCategory(currentKind,null)}>+ Fő kategória</button></div><div className="db-tree">{currentTree.map(root=>{const accent=root.color??"#D2D3D5";return <div className="db-tree-root" key={root.id} style={{"--accent":accent} as CSSProperties}><div className="db-root-label"><span className="db-root-swatch"/><span>{root.name}</span><small>{root.children.length} elem</small></div><div className="db-root-body"><CategoryNodeButton node={root} accent={accent} selectedId={selectedId} onSelect={selectNode}/></div></div>})}</div></section>}

  {tab==="people"&&<section className="panel db-simple-panel"><div className="panel-head"><div><h2>Személyek</h2><p className="muted db-help">Kiadásnál opcionális. Ha nincs személy, a kiadás közös.</p></div></div><div className="db-inline-create"><input className="input" value={personName} onChange={e=>setPersonName(e.target.value)} placeholder="Új személy"/><button className="secondary" onClick={addPerson} disabled={busy}>+ Hozzáadás</button></div><div className="db-list">{people.map((person,index)=><div className="db-list-row" key={person.id}><span className={`avatar pastel-${index%4+1}`}>{person.name.slice(0,1).toUpperCase()}</span><strong>{person.name}</strong><div><button className="ghost" onClick={()=>renamePerson(person)}>Átnevezés</button><button className="ghost danger-link" onClick={()=>removePerson(person)}>Törlés</button></div></div>)}</div></section>}
  {tab==="merchants"&&<section className="panel db-simple-panel"><div className="panel-head"><div><h2>Boltok / partnerek</h2><p className="muted db-help">A blokkfelismerés merchant-specifikus szabályai ezekhez a partnerekhez kapcsolódnak.</p></div></div><div className="db-inline-create"><input className="input" value={merchantName} onChange={e=>setMerchantName(e.target.value)} placeholder="Új bolt vagy partner"/><button className="secondary" onClick={addMerchant} disabled={busy}>+ Hozzáadás</button></div><div className="db-list">{merchants.map(merchant=><div className="db-list-row" key={merchant.id}><span className="merchant-glyph">⌂</span><strong>{merchant.name}</strong><div><button className="ghost" onClick={()=>renameMerchant(merchant)}>Átnevezés</button><button className="ghost danger-link" onClick={()=>removeMerchant(merchant)}>Törlés</button></div></div>)}</div></section>}

  {tab==="learning"&&<section className="panel db-simple-panel learning-manager"><div className="panel-head"><div><h2>AI tanulás</h2><p className="muted db-help">Itt látod és javíthatod, mit tanult meg a blokkfeldolgozó. Minden szabály kizárólag a bejelentkezett felhasználóhoz tartozik.</p></div><button className="secondary" onClick={()=>loadLearning()} disabled={learningLoading}>{learningLoading?"Frissítés…":"Frissítés"}</button></div><div className="learning-toolbar"><div className="db-tabs learning-tabs"><button className={learningView==="mapping"?"active learning":""} onClick={()=>setLearningView("mapping")}>Termékszabályok · {mappings.length}</button><button className={learningView==="structure"?"active learning":""} onClick={()=>setLearningView("structure")}>Split / Merge · {structureRules.length}</button></div><input className="input" value={learningFilter} onChange={e=>setLearningFilter(e.target.value)} placeholder="Keresés bolt, blokkszöveg, tétel vagy kategória alapján"/></div>
   {learningView==="mapping"&&<div className="learning-list">{visibleMappings.length===0&&!learningLoading&&<div className="db-empty">Még nincs megtanult termék-mapping.</div>}{visibleMappings.map(rule=><MappingEditor key={rule.id} rule={rule} categories={expenseCategories} busy={busy} onSave={(next)=>learningMutate("PATCH",{kind:"mapping",id:rule.id,...next},"A mapping frissítve.")} onDelete={()=>{if(confirm("Törlöd ezt a megtanult mappinget?"))void learningMutate("DELETE",{kind:"mapping",id:rule.id},"A mapping törölve.")}}/>)}</div>}
   {learningView==="structure"&&<div className="learning-list">{visibleStructures.length===0&&!learningLoading&&<div className="db-empty">Még nincs megtanult Split/Merge szabály.</div>}{visibleStructures.map(rule=><div className="learning-card" key={rule.id}><div className="learning-card-head"><div><span className={`structure-action ${rule.action.toLowerCase()}`}>{rule.action}</span><strong>{merchantLabel(rule.merchantNormalized)}</strong><small>Frissítve: {dateLabel(rule.updatedAt)}</small></div><button className="ghost danger-link" disabled={busy} onClick={()=>{if(confirm("Törlöd ezt a strukturális szabályt?"))void learningMutate("DELETE",{kind:"structure",id:rule.id},"A strukturális szabály törölve.")}}>Törlés</button></div><div className="structure-components">{rule.components.map((v,i)=><span key={i}>{String(v)}</span>)}</div>{rule.targetLabel&&<div className="learning-target"><span>Cél:</span><strong>{rule.targetLabel}</strong>{rule.targetCategoryPath&&<small>{rule.targetCategoryPath}</small>}</div>}<div className="learning-actions"><button className={rule.action==="SPLIT"?"primary":"secondary"} disabled={busy||rule.action==="SPLIT"} onClick={()=>learningMutate("PATCH",{kind:"structure",id:rule.id,action:"SPLIT"},"A legutolsó döntés most Split.")}>Split legyen aktív</button><button className={rule.action==="MERGE"?"primary":"secondary"} disabled={busy||rule.action==="MERGE"} onClick={()=>learningMutate("PATCH",{kind:"structure",id:rule.id,action:"MERGE"},"A legutolsó döntés most Merge.")}>Merge legyen aktív</button></div><p className="muted db-help">Az itt végzett módosítás frissíti a szabály időbélyegét, ezért ez lesz a legutolsó és aktív döntés ennél a kombinációnál.</p></div>)}</div>}
  </section>}

  {selected&&<><div className="db-modal-backdrop" onClick={closeInspector}/><aside className="db-category-modal" style={{"--modal-accent":selectedAccent} as CSSProperties}><div className="db-modal-accent"/><div className="db-modal-head"><div><div className="eyebrow">{selected.kind==="EXPENSE"?"Kiadási elem":"Bevételi elem"}</div><h2>{selected.name}</h2><p className="muted db-path">{flatPath}</p></div><button className="db-modal-close" onClick={closeInspector} aria-label="Bezárás">×</button></div>{selected.kind==="EXPENSE"&&<Link className="db-quick-add" href={`/app/add/expense?categoryId=${selected.id}&label=${encodeURIComponent(selected.name)}`}><span>＋</span><span><strong>Kiadás hozzáadása innen</strong><small>A kategória előre ki lesz választva</small></span><i>›</i></Link>}<div className="db-modal-section"><div className="field"><label>Név</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Színkód</label><div className="db-selected-color"><input className="color-input" type="color" value={selectedColor} onChange={e=>setSelectedColor(e.target.value)}/><span className="db-color-preview" style={{background:selectedColor}}/><code>{selectedColor.toUpperCase()}</code></div></div><button className="secondary db-wide-button" disabled={busy||!name.trim()} onClick={updateCategory}>Módosítások mentése</button></div>{selected.depth<3&&<div className="db-modal-section"><div className="db-section-title">Új elem alatta</div><div className="field"><input className="input" value={newName} onChange={e=>setNewName(e.target.value)} placeholder={selected.depth===2?"pl. Alma":"Új alkategória"}/></div><label className="check-chip db-item-toggle"><input type="checkbox" checked={newAsItem||selected.depth===2} disabled={selected.depth===2} onChange={e=>setNewAsItem(e.target.checked)}/>Kereshető tétel / megnevezés is</label><button className="secondary db-wide-button" disabled={busy} onClick={()=>addCategory(selected.kind,selected.id)}>+ Hozzáadás</button></div>}<div className="db-modal-section danger-section"><button className="ghost danger-link" disabled={busy} onClick={removeCategory}>Törlés / archiválás</button><p className="muted db-help">Ha korábbi pénzügyi adat használja, az elem archiválódik, a történeti adatok nem sérülnek.</p></div></aside></>}
 </div>;
}

function MappingEditor({rule,categories,busy,onSave,onDelete}:{rule:MappingRule;categories:Category[];busy:boolean;onSave:(next:Record<string,unknown>)=>void;onDelete:()=>void}){
 const [label,setLabel]=useState(rule.label),[categoryId,setCategoryId]=useState(rule.categoryId??"");
 const [attrs,setAttrs]=useState({isDairy:rule.isDairy,containsEgg:rule.containsEgg,containsAnimal:rule.containsAnimal,isAlcohol:rule.isAlcohol,isFrozen:rule.isFrozen,isCanned:rule.isCanned,isPackaged:rule.isPackaged});
 useEffect(()=>{setLabel(rule.label);setCategoryId(rule.categoryId??"");setAttrs({isDairy:rule.isDairy,containsEgg:rule.containsEgg,containsAnimal:rule.containsAnimal,isAlcohol:rule.isAlcohol,isFrozen:rule.isFrozen,isCanned:rule.isCanned,isPackaged:rule.isPackaged})},[rule]);
 const attrDefs:[keyof typeof attrs,string][]=[["isDairy","Tejtermék"],["containsEgg","Tojás"],["containsAnimal","Állati"],["isAlcohol","Alkohol"],["isFrozen","Fagyasztott"],["isCanned","Konzerv"],["isPackaged","Csomagolt"]];
 return <div className="learning-card"><div className="learning-card-head"><div><span className="mapping-scope-pill">{merchantLabel(rule.merchantNormalized)}</span><strong className="learning-raw">{rule.rawNormalized}</strong><small>Használat: {rule.usageCount} · Frissítve: {dateLabel(rule.updatedAt)}</small></div><button className="ghost danger-link" disabled={busy} onClick={onDelete}>Törlés</button></div><div className="learning-edit-grid"><div className="field"><label>Megtanult tétel</label><input className="input" value={label} onChange={e=>setLabel(e.target.value)}/></div><div className="field"><label>Kategória</label><select className="select" value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Nincs kategória</option>{categories.slice().sort((a,b)=>categoryPath(categories,a.id).localeCompare(categoryPath(categories,b.id),"hu")).map(c=><option key={c.id} value={c.id}>{categoryPath(categories,c.id)}</option>)}</select></div></div><div className="attr-row learning-attrs">{attrDefs.map(([key,text])=><label className="check-chip" key={key}><input type="checkbox" checked={attrs[key]} onChange={e=>setAttrs(v=>({...v,[key]:e.target.checked}))}/>{text}</label>)}</div><div className="learning-actions"><button className="primary" disabled={busy||!label.trim()} onClick={()=>onSave({label:label.trim(),categoryId:categoryId||null,...attrs})}>Mapping mentése</button></div></div>;
}
