import { requireUser } from "@/lib/auth";
import { buildCategoryPath } from "@/lib/categories";
import { formatMoney } from "@/lib/money";
import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";

export default async function ReceiptDetailPage({params}:{params:Promise<{id:string}>}){
 const user=await requireUser();const {id}=await params;
 const [receipt,categories]=await Promise.all([prisma.receipt.findFirst({where:{id,userId:user.id},include:{merchant:true,person:true,lines:true,purchase:true}}),prisma.categoryNode.findMany({where:{userId:user.id,kind:"EXPENSE"}})]);if(!receipt)notFound();
 const processed=receipt.lines.reduce((s,l)=>s+Number(l.amount),0),declared=Number(receipt.declaredTotal??0),diff=declared-processed,unresolved=receipt.lines.filter(l=>!l.categoryId).length;
 return <main className="page"><div className="page-head"><div><div className="eyebrow">Lezárt blokk</div><h1 className="page-title">{receipt.merchant?.name??"Blokk"}</h1><p className="muted">{(receipt.purchaseDate??receipt.createdAt).toLocaleDateString("hu-HU")} · {receipt.person?.name??"Közös"} · Receipt ID: {receipt.id.slice(0,8)}</p></div><a className="secondary" href="/app/receipts">← Blokkok</a></div><section className={`receipt-reconcile detail ${Math.abs(diff)<=0.01&&unresolved===0?"receipt-match":"receipt-mismatch"}`}><div><span>Blokk végösszeg</span><strong>{formatMoney(declared,receipt.currency??"CHF")}</strong></div><div><span>Hozzáadott kiadások</span><strong>{formatMoney(processed,receipt.currency??"CHF")}</strong></div><div><span>Eltérés</span><strong>{diff.toFixed(2)} {receipt.currency} {Math.abs(diff)<=0.01?"✓":"⚠"}</strong></div><div><span>Tételek</span><strong>{receipt.lines.length}</strong></div><div><span>Nincs kategorizálva</span><strong>{unresolved}</strong></div></section><div className="panel receipt-detail-panel"><div className="panel-head"><div><h2>Feldolgozott tételek</h2><p className="muted section-note">A blokk lezárásakor az eredeti kép törlődött. A strukturált tételek és az ellenőrző matematika megmaradt.</p></div>{receipt.purchase&&<a className="text-link" href={`/app/history/expense/${receipt.purchase.id}`}>Kiadás megnyitása ›</a>}</div><div className="receipt-detail-lines">{receipt.lines.map((l,i)=><div className="receipt-detail-line" key={l.id}><span className="receipt-line-number">{i+1}</span><span className="receipt-detail-copy">{l.rawLabel&&<small>{l.rawLabel}</small>}<strong>{l.label}</strong><em>{l.categoryId?buildCategoryPath(l.categoryId,categories):"Nincs kategorizálva"}</em></span><strong>{formatMoney(Number(l.amount),receipt.currency??"CHF")}</strong></div>)}</div></div>{receipt.note&&<div className="panel"><h2>Megjegyzés</h2><p>{receipt.note}</p></div>}</main>
}
